### ISSUE TITLE
Make the programs compatible with Chrome

### ISSUE THREAD

**Issue by lars-t-hansen** [lars-t-hansen/parlib-simple#31]
Chrome has SharedArrayBuffer and Atomics when some flags are set at startup.  But many of the test cases do not run in Chrome because I use JS features that Chrome does not yet have:
- global (or even local?) "let" and "const" outside strict mode
- array destructuring, to pick apart data sent by messages between workers

Mostly it's a matter of slapping "use strict" on the top of each JS file that does not have them and to rewrite the destructuring using explicit bindings and assignments.  It would be good to be able to run all these programs in Chrome.  (It's good for all the programs to be strict in any case.)

**Comment by lars-t-hansen** [comment]
Run Chrome with these flags:
--js-flags=--harmony-sharedarraybuffer --enable-blink-feature=SharedArrayBuffer

**Comment by eranimo** [comment]
Both of the above features now work in chrome without flags, so this issue can be closed
